version: 2

project_name: opencode-sync

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: opencode-sync
    main: ./cmd/opencode-sync
    binary: opencode-sync
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/GareArc/opencode-sync/internal/cli.version={{.Version}}
      - -X github.com/GareArc/opencode-sync/internal/cli.commit={{.Commit}}
      - -X github.com/GareArc/opencode-sync/internal/cli.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: GareArc
    name: opencode-sync
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

brews:
  - name: opencode-sync
    repository:
      owner: GareArc
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/GareArc/opencode-sync"
    description: "Sync OpenCode configurations across machines via Git with optional encryption"
    license: "MIT"

scoops:
  - name: opencode-sync
    repository:
      owner: GareArc
      name: scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}"
    directory: bucket
    homepage: "https://github.com/GareArc/opencode-sync"
    description: "Sync OpenCode configurations across machines via Git with optional encryption"
    license: "MIT"
